/**
 * ⚠️  DATOS MOCK — SOLO DESARROLLO  ⚠️
 *
 * Productos ficticios para poder maquetar y probar la tienda mientras la
 * tabla equipment_products de Supabase está vacía. NO son productos, marcas,
 * precios ni stock reales. Nunca se sirven en producción (ver equipment.ts).
 */
import type { EquipmentProduct } from "./types";
import { rowToEquipment, type EquipmentRow } from "./equipment-mapper";

const base = {
  sku: null,
  ean: null,
  subcategory: null,
  images: [],
  colors: [],
  sizes: [],
  stock: 0,
  rating: null,
  review_count: 0,
  features: [],
  materials: [],
  technology: [],
  gender: null,
  season: null,
  tags: [],
  badges: [],
  faq: [],
  compare_at_price: null,
} satisfies Partial<EquipmentRow>;

function variants(prefix: string, colors: string[], sizes: string[], stockFn: (i: number) => number) {
  let i = 0;
  return colors.flatMap((color) =>
    sizes.map((size) => ({ sku: `${prefix}-${color}-${size}`.toUpperCase().replace(/\s+/g, ""), ean: null, color, size, stock: stockFn(i++), price: null })),
  );
}

const ROWS: EquipmentRow[] = [
  {
    ...base,
    id: "mock-1",
    slug: "demo-casco-integral",
    sku: "DEMO-CI-01",
    brand: "Marca Demo",
    name: "[DEMO] Casco integral",
    category: "cascos",
    type: "integral",
    description: "Producto de ejemplo para desarrollo. Sustituir por catálogo real.",
    price: 129.9,
    compare_at_price: 159.9,
    colors: [{ name: "Negro", hex: "#16171a" }, { name: "Blanco", hex: "#f2f2f2" }],
    rating: 4.5,
    review_count: 12,
    features: ["Característica de ejemplo 1", "Característica de ejemplo 2"],
    materials: ["Material de ejemplo"],
    badges: ["bestseller"],
    tags: ["negro", "blanco", "carretera"],
    faq: [{ q: "¿Pregunta de ejemplo?", a: "Respuesta de ejemplo." }],
    equipment_variants: variants("DEMO-CI", ["Negro", "Blanco"], ["S", "M", "L", "XL"], (i) => (i % 5 === 0 ? 0 : 4)),
  },
  {
    ...base,
    id: "mock-2",
    slug: "demo-casco-modular",
    brand: "Marca Demo",
    name: "[DEMO] Casco modular",
    category: "cascos",
    type: "modular",
    description: "Producto de ejemplo para desarrollo.",
    price: 219,
    colors: [{ name: "Gris", hex: "#6b6f76" }],
    badges: ["new"],
    tags: ["gris", "viaje"],
    equipment_variants: variants("DEMO-CM", ["Gris"], ["M", "L", "XL"], () => 2),
  },
  {
    ...base,
    id: "mock-3",
    slug: "demo-casco-off-road",
    brand: "Otra Marca Demo",
    name: "[DEMO] Casco off-road",
    category: "cascos",
    type: "off-road",
    description: "Producto de ejemplo para desarrollo.",
    price: 99.95,
    colors: [{ name: "Negro", hex: "#16171a" }, { name: "Rojo", hex: "#c8261e" }],
    rating: 4,
    review_count: 3,
    tags: ["negro", "rojo", "enduro"],
    equipment_variants: variants("DEMO-CO", ["Negro", "Rojo"], ["S", "M", "L"], () => 6),
  },
  {
    ...base,
    id: "mock-4",
    slug: "demo-casco-jet",
    brand: "Marca Demo",
    name: "[DEMO] Casco jet",
    category: "cascos",
    type: "jet",
    description: "Producto de ejemplo para desarrollo.",
    price: 74.9,
    colors: [{ name: "Blanco", hex: "#f2f2f2" }],
    tags: ["blanco", "ciudad"],
    equipment_variants: variants("DEMO-CJ", ["Blanco"], ["S", "M", "L"], () => 0),
  },
  {
    ...base,
    id: "mock-5",
    slug: "demo-guantes-verano",
    brand: "Marca Demo",
    name: "[DEMO] Guantes de verano",
    category: "guantes",
    type: "verano",
    description: "Producto de ejemplo para desarrollo.",
    price: 39.9,
    compare_at_price: 49.9,
    colors: [{ name: "Negro", hex: "#16171a" }],
    rating: 5,
    review_count: 7,
    tags: ["negro"],
    equipment_variants: variants("DEMO-GV", ["Negro"], ["S", "M", "L", "XL"], () => 8),
  },
  {
    ...base,
    id: "mock-6",
    slug: "demo-guantes-invierno",
    brand: "Otra Marca Demo",
    name: "[DEMO] Guantes de invierno impermeables",
    category: "guantes",
    type: "invierno",
    description: "Producto de ejemplo para desarrollo.",
    price: 59.9,
    colors: [{ name: "Negro", hex: "#16171a" }],
    tags: ["negro", "impermeable"],
    season: "invierno",
    equipment_variants: variants("DEMO-GI", ["Negro"], ["M", "L", "XL"], () => 3),
  },
  {
    ...base,
    id: "mock-7",
    slug: "demo-chaqueta-textil",
    brand: "Marca Demo",
    name: "[DEMO] Chaqueta textil adventure",
    category: "chaquetas",
    type: "adventure",
    description: "Producto de ejemplo para desarrollo.",
    price: 249,
    compare_at_price: 299,
    colors: [{ name: "Gris", hex: "#6b6f76" }, { name: "Negro", hex: "#16171a" }],
    rating: 4.5,
    review_count: 4,
    badges: ["new"],
    tags: ["gris", "negro", "textil"],
    equipment_variants: variants("DEMO-CT", ["Gris", "Negro"], ["S", "M", "L", "XL", "XXL"], (i) => i % 3),
  },
  {
    ...base,
    id: "mock-8",
    slug: "demo-chaqueta-cuero",
    brand: "Otra Marca Demo",
    name: "[DEMO] Chaqueta de cuero",
    category: "chaquetas",
    type: "cuero",
    description: "Producto de ejemplo para desarrollo.",
    price: 329,
    colors: [{ name: "Negro", hex: "#16171a" }],
    tags: ["negro"],
    equipment_variants: variants("DEMO-CC", ["Negro"], ["M", "L", "XL"], () => 1),
  },
  {
    ...base,
    id: "mock-9",
    slug: "demo-camiseta",
    brand: "Marca Demo",
    name: "[DEMO] Camiseta manga corta",
    category: "camisetas",
    type: "manga-corta",
    description: "Producto de ejemplo para desarrollo.",
    price: 24.9,
    colors: [{ name: "Negro", hex: "#16171a" }, { name: "Azul", hex: "#1F3F7A" }],
    tags: ["negro", "azul"],
    equipment_variants: variants("DEMO-CA", ["Negro", "Azul"], ["S", "M", "L", "XL"], () => 10),
  },
  {
    ...base,
    id: "mock-10",
    slug: "demo-botas-touring",
    brand: "Marca Demo",
    name: "[DEMO] Botas touring",
    category: "botas",
    type: "touring",
    description: "Producto de ejemplo para desarrollo.",
    price: 179,
    colors: [{ name: "Negro", hex: "#16171a" }],
    rating: 4,
    review_count: 2,
    badges: ["bestseller"],
    tags: ["negro"],
    equipment_variants: variants("DEMO-BT", ["Negro"], ["40", "41", "42", "43", "44", "45"], () => 2),
  },
  {
    ...base,
    id: "mock-11",
    slug: "demo-botas-off-road",
    brand: "Otra Marca Demo",
    name: "[DEMO] Botas off-road",
    category: "botas",
    type: "off-road",
    description: "Producto de ejemplo para desarrollo.",
    price: 239,
    compare_at_price: 269,
    colors: [{ name: "Blanco", hex: "#f2f2f2" }],
    tags: ["blanco", "enduro"],
    equipment_variants: variants("DEMO-BO", ["Blanco"], ["41", "42", "43", "44"], () => 5),
  },
];

export const MOCK_EQUIPMENT: EquipmentProduct[] = ROWS.map((r, i) => ({
  ...rowToEquipment({ ...r, featured: i % 2 === 0 }),
  isMock: true,
}));

export const MOCK_FEATURED_IDS = new Set(ROWS.filter((_, i) => i % 2 === 0).map((r) => r.id));
